id: P007084
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG20788
  title: འཕགས་ཡུལ་རྒྱ་ནག་ཆེན་པོ་བོད་དང་སོག་ཡུལ་རྣམས་སུ་དམ་པའི་ཆོས་བྱུང་ཚུལ་དཔག་བསམ་ལྗོན་བཟང་།
  author: ''
  volumes:
    04fe9368bae2406a86f50c42931345d5:
      image_group_id: I1KG20838
      title: ''
      volume_number: 1
      total_pages: 244
    9ed5dbffb1414e39b8d6f0e08b0d0c36:
      image_group_id: I1KG20839
      title: ''
      volume_number: 2
      total_pages: 384
ebook_metadata:
  title: འཕགས་ཡུལ་རྒྱ་ནག་ཆེན་པོ་བོད་དང་སོག་ཡུལ་རྣམས་སུ་དམ་པའི་ཆོས་བྱུང་ཚུལ་དཔག་བསམ་ལྗོན་བཟང་།
  author: ''
  sku: P007084
  cover: cover.jpg
  layers:
  - pagination
