id: P007084
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG20788
  title: འཕགས་ཡུལ་རྒྱ་ནག་ཆེན་པོ་བོད་དང་སོག་ཡུལ་རྣམས་སུ་དམ་པའི་ཆོས་བྱུང་ཚུལ་དཔག་བསམ་ལྗོན་བཟང་།
  author: ''
  volumes:
    e31353cb0e11488cb68ba54ed3107f1c:
      image_group_id: I1KG20838
      title: Volume 1 of 'phags yul rgya nag chen po bod dang sog yul rnams su dam
        pa'i chos byung tshul dpag bsam ljon bzang /
      volume_number: 1
      total_pages: 244
      base_file: v001.txt
    0a67cb5479ca409bba234331fd4c05a5:
      image_group_id: I1KG20839
      title: Volume 2 of 'phags yul rgya nag chen po bod dang sog yul rnams su dam
        pa'i chos byung tshul dpag bsam ljon bzang /
      volume_number: 2
      total_pages: 384
      base_file: v002.txt
