id: opecha:P007084
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG20788
  title: འཕགས་ཡུལ་རྒྱ་ནག་ཆེན་པོ་བོད་དང་སོག་ཡུལ་རྣམས་སུ་དམ་པའི་ཆོས་བྱུང་ཚུལ་དཔག་བསམ་ལྗོན་བཟང་།
  volume: ''
  author: ''
