id: I58F6F004
legacy_id: P007084
ocr_import_info:
  bdrc_scan_id: W1KG20788
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T21:15:47'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T10:28:33.734812+00:00'
last_modified: 2022-08-31 18:29:01.704621
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG20788
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG20788
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཕགས་ཡུལ་རྒྱ་ནག་ཆེན་པོ་བོད་དང་སོག་ཡུལ་རྣམས་སུ་དམ་པའི་ཆོས་བྱུང་ཚུལ་དཔག་བསམ་ལྗོན་བཟང་།
  author: སུམ་པ་མཁན་པོ་ཡེ་ཤེས་དཔལ་འབྱོར།
statistics:
  ocr_word_mean_confidence_index: 0.6492592933009427
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I1KG20839:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG20839
      total_pages: 384
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG20839.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7544355388485788
    legacy_id: v002
  I1KG20838:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG20838
      total_pages: 244
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG20838.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5091994358061634
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
